const express = require("express");
const router = express.Router();
const adminRoute = require("../routes/admin.route.js");
const authRoute = require("../routes/auth.routes.js");
const studentRoute = require("../routes/student.routes.js");
const departmentRoute = require("../routes/department.routes.js");
const courseRoute = require("../routes/course.routes.js");
const subjectRoute = require("../routes/subject.routes.js");
const studentSubjectRoute = require("../routes/studentSubject.routes.js");
const semesterRoute = require("../routes/semester.routes.js");
const admissionRoute = require("../routes/admission.routes.js");
const paymentRoute = require("../routes/payment.routes.js");
const fileRoute = require("../routes/file.routes.js");
const auditRoute = require("../routes/audit.routes.js");
const certificateRoute = require("../routes/certificate.routes.js");
const cmsRoute = require("../routes/cms.routes.js");
const sessionRoute = require("../routes/session.routes.js");
const adminDashboardRoute = require("../routes/adminDashboard.routes.js");

router.use("/auth", authRoute);
router.use("/admin", adminRoute);
router.use("/students", studentRoute);
router.use("/departments", departmentRoute);
router.use("/courses", courseRoute);
router.use("/subjects", subjectRoute);
router.use("/student-subjects", studentSubjectRoute);
router.use("/semesters", semesterRoute);
router.use("/admissions", admissionRoute);
router.use("/payments", paymentRoute);
router.use("/files", fileRoute);
router.use("/audit", auditRoute);
router.use("/certificates", certificateRoute);
router.use("/cms", cmsRoute);
router.use("/sessions", sessionRoute);
router.use("/admin-dashboard", adminDashboardRoute);

module.exports = router;